// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqWgIdqIrr8tF73vcIrLpy9_fwHA7G7Wc',
    appId: '1:465326757288:web:31a6645d4b8c5e5710799d',
    messagingSenderId: '465326757288',
    projectId: 'pokemon-ca507',
    authDomain: 'pokemon-ca507.firebaseapp.com',
    storageBucket: 'pokemon-ca507.firebasestorage.app',
    measurementId: 'G-0B9GNGMLBF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhYWqLOyw5ROCpwXfHNEVXTeprRDMzSvA',
    appId: '1:465326757288:android:0f2ebddc06ad110b10799d',
    messagingSenderId: '465326757288',
    projectId: 'pokemon-ca507',
    storageBucket: 'pokemon-ca507.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyfv_OtTCzzqLVyHBzj9HhBJ1HDjA04OY',
    appId: '1:465326757288:ios:50dec8b55cb38f5010799d',
    messagingSenderId: '465326757288',
    projectId: 'pokemon-ca507',
    storageBucket: 'pokemon-ca507.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyfv_OtTCzzqLVyHBzj9HhBJ1HDjA04OY',
    appId: '1:465326757288:ios:50dec8b55cb38f5010799d',
    messagingSenderId: '465326757288',
    projectId: 'pokemon-ca507',
    storageBucket: 'pokemon-ca507.firebasestorage.app',
    iosBundleId: 'com.example.helloFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqWgIdqIrr8tF73vcIrLpy9_fwHA7G7Wc',
    appId: '1:465326757288:web:c23f914fa43da92e10799d',
    messagingSenderId: '465326757288',
    projectId: 'pokemon-ca507',
    authDomain: 'pokemon-ca507.firebaseapp.com',
    storageBucket: 'pokemon-ca507.firebasestorage.app',
    measurementId: 'G-9DKZNYQJ14',
  );
}
